/* eslint-disable */
export const fetchPets = [
  {
    id: "nKIAw7fUCSxCvgA2MzwS",
    name: "Bella",
    description:
      "Cats are believed to be the only mammals who don't taste sweetness.",
    age: 8,
    type: "cat",
    created: "August 30, 2022 at 10:21:06 AM UTC-5",
    donationAmt: "",
    expOwner: true,
    img: "cat.jpeg",
    isKidFriendly: true,
  },
  {
    id: "c8rvgG2RnKmMmbseo38w",
    created: "August 30, 2022 at 10:21:06 AM UTC-5",
    description:
      "Soft kitty, warm kitty, little ball of fur! Happy kitty, sleepy kitty, purr purr purr!",
    donationAmt: "",
    expOwner: true,
    img: "cat1.jpeg",
    isKidFriendly: true,
    name: "Lila",
    type: "cat",
    age: 1,
  },
  {
    id: "hirlTm8MS1SHeQqAyytk",
    type: "cat",
    created: "August 30, 2022 at 10:21:06 AM UTC-5",
    description:
      "Cats are nearsighted, but their peripheral vision and night vision are much better than that of humans.",
    donationAmt: "",
    expOwner: true,
    img: "cat2.jpeg",
    isKidFriendly: true,
    name: "Steven",
    age: 5,
  },
  {
    id: "nKIAw7fUCSxCvgA2MzwS",
    type: "dog",
    created: "August 30, 2022 at 10:21:06 AM UTC-5",
    description:
      "Jump, jump, jump, jump, yap, yap, yap, yap, bark, bark, bark, bark, whine",
    donationAmt: "",
    expOwner: true,
    img: "dog2.jpeg",
    isKidFriendly: true,
    name: "Wilbur",
    age: 10,
  },
  {
    id: "2KZZsRi79VySdJzgP5QG",
    type: "cat",
    age: 15,
    created: "August 30, 2022 at 10:21:06 AM UTC-5",
    description:
      "Cats are supposed to have 18 toes (five toes on each front paw; four toes on each back paw).",
    donationAmt: "",
    expOwner: true,
    img: "cat3.jpeg",
    isKidFriendly: true,
    name: "Xavier",
  },
  {
    id: "bRaxar8xLSIDhjitmVIk",
    type: "horse",
    age: 3,
    created: "August 30, 2022 at 10:21:06 AM UTC-5",
    description: "This is a horse, not a dog. The picture lies.",
    donationAmt: "",
    expOwner: true,
    img: "dog3.jpeg",
    isKidFriendly: true,
    name: "Barnaby",
  },
  {
    id: "I0dI4X7DJbRRzK5XRWpH",
    name: "Ol' Ben",
    adoptable: false,
    age: 8,
    created: "August 30, 2022 at 10:21:06 AM UTC-5",
    description: "This is a dog",
    donationAmt: "",
    expOwner: true,
    img: "",
    isKidFriendly: true,
    img: "dog1.jpeg",
    type: "dog",
  },
  {
    id: "w1pqFsZ3XEGahuhWJmoS",
    type: "dog",
    age: 2,
    description:
      "The area of cells in the brain that detect different smells is around 40 times larger in dogs than humans. What I am trying to say is... you smell but I still love you.",
    img: "dog4.jpeg",
    name: "Cute Puppers",
  },
  {
    id: "rYezcsiM1DPiVXO8x20Z",
    type: "horse",
    description: "horse",
    img: "",
    name: "horse1",
  },
  {
    id: "jrL7gNpqvKM5AXukd0px",
    type: "horse",
    img: "",
    description: "horse2",
    name: "horse2",
  },
  {
    id: "fUI7E2YWHa5voMfUNswH",
    type: "dog",
    img: "",
    name: "dog5",
    description: "dog5",
  },
  {
    created: "September 3, 2022 at 12:41:16 AM UTC-5",
    id: "cSMCvPhYslwU3cxBNwOo",
    img: "",
    name: "donkey",
  },
  {
    created: "September 3, 2022 at 12:40:58 AM UTC-5",
    id: "zDsEmw5RO4QBxHWvPt5s",
    img: "",
  },
  {
    created: "September 3, 2022 at 12:40:39 AM UTC-5",
    id: "V3qNKd4P35k5VZhay15Q",
    img: "",
    name: "bird",
  },
];

export const products = [
  {
    id: 1,
    category: "toy",
    image: "",
    name: "squeaky toy",
    price: 94.95,
    skus: "123456abc",
    description: "This rugged boot will get you up the mountain safely.",
  },
  {
    id: 2,
    category: "treats",
    image: "",
    name: "rawhide",
    price: 18.99,
    skus: "4321yxyxyx",
    description: "Sure-footed traction in slippery conditions.",
  },
  {
    id: 3,
    category: "food",
    image: "",
    name: "Yummy Dog Food",
    price: 45.95,
    description: "Look stylish while stomping in the mud.",
  },
];

export default fetchPets;
