export const products = [
  {
    category: "food",
    pet: "cat",
    food_type: "kibble",
    age: "adult",
    product_code: "",
    name: "Hill's® Science Diet® Sensitive Stomach & Skin Adult Dry Cat Food - Chicken",
    detail: "Cat food",
    category_id: 1,
    quantity_on_hand: 2,
    vendor_price: 18.99,
    weight: 3.5,
    weight_increments: "lb",
    retail_price: 22.49,
    vendor_discount: 0,
    v_discount_type: "",
    store_discount: 0,
    s_discount_type: "",
    vendor_id: 1234,
    status: 1,
    img: "",
    flavor: "chicken",
    health_consideration: ["Skin & Coat", "Digestive Care"],
    ingredients: [],
    item_no: 5012741,
    vendor_name: "Hill's Science Diet",
    rating: undefined,
  },
  {
    category: "food",
    pet: "cat",
    food_type: "kibble",
    age: "adult",
    product_code: "",
    name: "Hill's® Science Diet® Sensitive Stomach & Skin Adult Dry Cat Food - Chicken",
    detail: "Cat food",
    category_id: 1,
    quantity_on_hand: 1,
    vendor_price: 45.99,
    weight: 15.5,
    weight_increments: "lb",
    retail_price: 53.99,
    vendor_discount: 0,
    v_discount_type: "",
    store_discount: 0,
    s_discount_type: "",
    vendor_id: 1234,
    status: 1,
    img: "",
    flavor: "chicken",
    health_consideration: ["Skin & Coat", "Digestive Care"],
    ingredients: [],
    item_no: 5154821,
    vendor_name: "Hill's Science Diet",
    rating: undefined,
  },
  {
    category: "food",
    pet: "cat",
    food_type: "kibble",
    age: "adult",
    product_code: "",
    name: "Hill's® Science Diet® Indoor Adult Dry Cat Food - Chicken",
    detail: "Cat food",
    category_id: 1,
    quantity_on_hand: 3,
    vendor_price: 25.0,
    weight: 7,
    weight_increments: "lb",
    retail_price: 31.49,
    vendor_discount: 0,
    v_discount_type: "",
    store_discount: 0,
    s_discount_type: "",
    vendor_id: 1234,
    status: 1,
    img: "",
    flavor: "chicken",
    health_consideration: ["Skin & Coat", "Digestive Care"],
    ingredients: [],
    item_no: 5154809,
    vendor_name: "Hill's Science Diet",
    rating: undefined,
  },
  {
    category: "food",
    pet: "cat",
    food_type: "kibble",
    age: "adult",
    product_code: "",
    name: "Hill's® Science Diet® Indoor Adult Dry Cat Food - Chicken",
    detail: "Cat food",
    category_id: 1,
    quantity_on_hand: 4,
    vendor_price: 19.99,
    weight: 3.5,
    weight_increments: "lb",
    retail_price: 22.99,
    vendor_discount: 0,
    v_discount_type: "",
    store_discount: 0,
    s_discount_type: "",
    vendor_id: 1234,
    status: 1,
    img: "",
    health_consideration: [],
    flavor: "chicken",
    ingredients: [],
    item_no: 5102283,
  },
  {
    category: "food",
    pet: "cat",
    food_type: "kibble",
    life_stage: "adult",
    product_code: "",
    name: "Hill's® Science Diet® Sensitive Stomach & Skin Adult Dry Cat Food - Chicken",
    detail:
      "Hill's Science Diet Sensitive Stomach & Skin dry cat food is a highly digestible food helps ensure nutrient absorption while being gentle on your pet's stomach. This food is specially formulated with Vitamin E & Omega-6 fatty acids to help maintain and protect skin and fur. It also contains added FOS, a nourishing prebiotic fiber, and is a highly digestible food that is gentle on the stomach.",
    category_id: 1,
    quantity_on_hand: 5,
    vendor_price: 29.99,
    weight: undefined,
    weight_increments: "",
    weight_string: "7 lb (3.175 kg); 24.6 cups per bag",
    retail_price: 35.49,
    vendor_discount: 0,
    v_discount_type: "",
    store_discount: 0,
    s_discount_type: "",
    vendor_id: 1234,
    status: 1,
    img: "",
    flavor: "chicken",
    health_consideration: [],
    ingredients: [],
    item_no: 5154820,
  },
  {
    category: "food",
    pet: "cat",
    food_type: "kibble",
    age: "adult",
    product_code: "",
    name: "Hill's® Science Diet® Indoor Adult Dry Cat Food - Chicken",
    detail: "Cat food",
    category_id: 1,
    quantity_on_hand: 4,
    vendor_price: 45.99,
    weight: 15.5,
    weight_increments: "lb",
    retail_price: 49.99,
    vendor_discount: 0,
    v_discount_type: "",
    store_discount: 0,
    s_discount_type: "",
    vendor_id: 1234,
    status: 1,
    img: "",
    health_consideration: [],
    flavor: "chicken",
    ingredients: [],
    item_no: 5154810,
  },
  {
    category: "food",
    pet: "cat",
    food_type: "kibble",
    age: "kitten",
    product_code: "",
    name: "Hill's® Science Diet® Indoor Kitten Dry Cat Food - Chicken",
    detail: "Hill's Science Diet Indoor Kitten dry food is specially formulated to fuel the energy needs of kittens with an indoor lifestyle so they get the best start in life. Help your kitten to grow up healthy and strong by serving this delicious dry blend.",
    category_id: 1,
    quantity_on_hand: 2,
    vendor_price: 34.99,
    weight: 7,
    weight_increments: "lb",
    retail_price: 31.99,
    vendor_discount: 0,
    v_discount_type: "",
    store_discount: 0,
    s_discount_type: "",
    vendor_id: 1234,
    status: 1,
    img: "",
    health_consideration: ["Pregnant and Nursing Female"],
    flavor: "chicken",
    ingredients: [],
    item_no: 5154806,
  },
  {
    category: "food",
    pet: "cat",
    food_type: "kibble",
    age: "kitten",
    product_code: "",
    name: "Hill's® Science Diet® Indoor Kitten Dry Cat Food - Chicken",
    detail: "Hill's Science Diet Indoor Kitten dry food is specially formulated to fuel the energy needs of kittens with an indoor lifestyle so they get the best start in life. Help your kitten to grow up healthy and strong by serving this delicious dry blend.",
    category_id: 1,
    quantity_on_hand: 2,
    vendor_price: 15.99,
    weight: 3.5,
    weight_increments: "lb",
    retail_price: 19.99,
    vendor_discount: 0,
    v_discount_type: "",
    store_discount: 0,
    s_discount_type: "",
    vendor_id: 1234,
    status: 1,
    img: "",
    health_consideration: ["Pregnant and Nursing Female"],
    flavor: "chicken",
    ingredients: [],
    item_no: 5154806,
  },
];
